repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
    - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: debug-statements

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear==20.1.4]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
    - id: pyupgrade
      args: [--py36-plus]

  - repo: https://github.com/mgedmin/check-python-versions
    rev: 0.17.0
    hooks:
    - id: check-python-versions

  - repo: https://github.com/mgedmin/check-manifest
    rev: '0.45'
    hooks:
    - id: check-manifest

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    - id: bandit
      args:
      - --skip
      - B101
